# Generated by Django 5.2.3 on 2025-07-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='Category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Succulent', 'Succulent'), ('Cactus', 'Cactus'), ('Herb', 'Herb'), ('Flowering', 'Flowering'), ('Foliage', 'Foliage'), ('Tree', 'Tree'), ('Shrub', 'Shrub'), ('Vine', 'Vine'), ('Pots', 'Pots'), ('Seeds', 'Seeds'), ('Ornamental', 'Ornamental'), ('Medicinal', 'Medicinal')]),
        ),
    ]
