# Generated by Django 5.2.3 on 2025-06-29 07:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='img/profile-placeholder.png', max_length=255),
        ),
    ]
